src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img_path;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $category_color;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="categories")
     */
    private $parent_category;

    /**
     * @ORM\OneToMany(targetEntity=Category::class, mappedBy="parent_category")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=Expense::class, mappedBy="category_new")
     */
    private $expenses;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sort_order;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->expenses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    public function getImgPath(): ?string
    {
        return $this->img_path;
    }

    public function setImgPath(?string $img_path): self
    {
        $this->img_path = $img_path;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategoryColor(): ?string
    {
        return $this->category_color;
    }

    public function setCategoryColor(?string $category_color): self
    {
        $this->category_color = $category_color;

        return $this;
    }

    public function getParentCategory(): ?self
    {
        return $this->parent_category;
    }

    public function setParentCategory(?self $parent_category): self
    {
        $this->parent_category = $parent_category;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(self $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setParentCategory($this);
        }

        return $this;
    }

    public function removeCategory(self $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getParentCategory() === $this) {
                $category->setParentCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Expense[]
     */
    public function getExpenses(): Collection
    {
        return $this->expenses;
    }

    public function addExpense(Expense $expense): self
    {
        if (!$this->expenses->contains($expense)) {
            $this->expenses[] = $expense;
            $expense->setCategory($this);
        }

        return $this;
    }

    public function removeExpense(Expense $expense): self
    {
        if ($this->expenses->removeElement($expense)) {
            // set the owning side to null (unless already changed)
            if ($expense->getCategory() === $this) {
                $expense->setCategory(null);
            }
        }

        return $this;
    }

    public function getSortOrder(): ?int
    {
        return $this->sort_order;
    }

    public function setSortOrder(?int $sort_order): self
    {
        $this->sort_order = $sort_order;

        return $this;
    }
}

src/Controller/ExpensesController.php
<?php

namespace App\Controller;

use App\Provider\Interfaces\CategoryProviderInterface;
use App\Provider\Interfaces\ExpensesProviderInterface;
use App\RequestProcessor\Interfaces\ExpenseRequestProcessorInterface;
use App\Service\Interfaces\ExpensesServiceInterface;
use App\Utils\DateProvider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ExpensesController extends AbstractController
{
    private $categoryProvider;
    private $requestProcessor;
    private $expenseService;
    private $expensesProvider;

    public function __construct(
        CategoryProviderInterface        $categoryProvider,
        ExpenseRequestProcessorInterface $expenseRequestProcessor,
        ExpensesServiceInterface         $expenseService,
        ExpensesProviderInterface        $expensesProvider
    )
    {
        $this->categoryProvider = $categoryProvider;
        $this->requestProcessor = $expenseRequestProcessor;
        $this->expenseService = $expenseService;
        $this->expensesProvider = $expensesProvider;
    }

    /**
     * @Route("/add-expense", name="add_expense_form", methods={"GET|POST"})
     */
    public function index(Request $request, DateProvider $dateProvider): Response
    {
        $alert = (string)$request->query->get('alert');
        $alert_class = (string)$request->query->get('alert_class');
        $todayDate = $dateProvider->getTodayDate();

        if ($request->isMethod("POST")) {
            $params = $request->request->all();
            $expense = $this->requestProcessor->create($params, $this->getUser());
            //try catch?
            $this->expenseService->create($expense);
            $lastUsedDate = $dateProvider->getLastUsedDate($expense->getDate());

            $alert = "Expense " . $expense->getTitle() . " added successfully!";
            $alert_class = "alert-success";
        }

        $date = $lastUsedDate ?? $todayDate;

        return $this->render('expenses/index.html.twig', [
            'this_year' => $date['year'], 'this_month' => $date['month'], 'this_day' => $date['day'],
            'expenses' => $this->expensesProvider->getLastExpensesByUserId($this->getUser()->getId(), 5),
            'categories' => $this->categoryProvider->getAllParentCategories(),
            'alert' => $alert, 'alert_class' => $alert_class,
        ]);
    }
}

templates/expenses/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}MONEYTRACK | add expense{% endblock %}
{% block stylesheets %}{{ parent() }}{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="card card-body shadow">
                <h3 class="fw-bold m-0">Add expense</h3>
                <hr>
                <form action="{{ path('add_expense_form', {'this_year' : this_year, 'this_month' : this_month}) }}"
                      enctype="multipart/form-data" method="post">

                    <div class="row mb-3">
                        <label for="title" class="col-sm-3 col-form-label">Title</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="title" id="title" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="" class="col-sm-3 col-form-label"></label>
                        <div class="col-sm-9 d-flex">
                            <div class="form-check p-0 w-100">
                                <input class="form-check-input" type="radio" name="direction" id="expense"
                                       value="expense" checked>
                                <label class="form-check-label radio-button pt-3 pb-3" for="expense">
                                    Expense <img src="/assets/icons/expenseRadio.svg" class="img-fluid">
                                </label>
                            </div>
                            <div class="form-check p-0 w-100">
                                <input class="form-check-input" type="radio" name="direction" id="income"
                                       value="income">
                                <label class="form-check-label radio-button pt-3 pb-3" for="income">
                                    Income <img src="/assets/icons/incomeRadio.svg" class="img-fluid">
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="date" class="col-sm-3 col-form-label">Date</label>
                        <div class="col-sm-9">
                            <input type="date" class="form-control" name="date" id="date"
                                   value="{{ this_year }}-{{ this_month }}-{{ this_day }}"
                                   required
                            >
                        </div>
                    </div>

                    <div class="expense-fields" id="expense-fields">
                        <div class="row mb-3">
                            <label for="category" class="col-sm-3 col-form-label">Category</label>
                            <div class="col-sm-9">
                                <select class="form-control expense-field" id="category" name="category">
                                    {% for cat in categories %}
                                        {% if cat.getCategories is not empty %}
                                            <optgroup label="{{ cat.getCategoryName() }}">
                                                <option value="{{ cat.getCategoryName() }}">
                                                    <b>{{ cat.getCategoryName() }}</b></option>
                                                {% for subCat in cat.getCategories %}
                                                    <option value="{{ subCat.getCategoryName() }}" {{ loop.first ? 'id="default"' : '' }}>{{ subCat.getCategoryName() }}</option>
                                                {% endfor %}
                                            </optgroup>
                                        {% elseif cat.getCategories is empty and cat.parentCategory is null %}
                                            <option value="{{ cat.getCategoryName() }}" {{ loop.first ? 'id="default"' : '' }}>{{ cat.getCategoryName() }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="recipient" class="col-sm-3 col-form-label">Recipient</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control expense-field" name="recipient"
                                       id="recipient"
                                       value="other" required>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="" class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 d-flex">
                                <div class="form-check p-0 w-100">
                                    <input class="form-check-input" type="radio" name="payer" id="self"
                                           value="self" checked>
                                    <label class="form-check-label radio-button pt-3 pb-3" for="self">
                                        Self <img src="/assets/icons/payer.svg" class="img-fluid">
                                    </label>
                                </div>
                                <div class="form-check p-0 w-100">
                                    <input class="form-check-input" type="radio" name="payer" id="notSelf"
                                           value="notSelf">
                                    <label class="form-check-label radio-button pt-3 pb-3" for="notSelf">
                                        Not self <img src="/assets/icons/notPayer.svg" class="img-fluid">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="amount" class="col-sm-3 col-form-label">Amount</label>
                        <div class="col-sm-9">
                            <input type="number" class="form-control" name="amount" id="amount" step="0.01"
                                   required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="amount" class="col-sm-3 col-form-label"></label>
                        <div class="col-sm-9 d-grid">
                            <button type="submit" class="btn btn-primary btn-sm">Save</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <div class="card card-body shadow">
                <h3 class="fw-bold">Your last transactions</h3>
                {% for expense in expenses %}
                    <div class="card card-body bg-light border py-2 my-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex align-items-center">
                                <div class="border rounded-circle p-2">
                                    <a href="#">
                                        <img src="/assets/icons/{{ expense.getCategory().categoryName|slug }}.svg"
                                             class="img-fluid" style="width: 36px; height: 36px;">
                                    </a>
                                </div>
                                <div class="pl-3">
                                    <div class="d-flex flex-column">
                                        <div class=""><b>{{ expense.getTitle() }}</b></div>
                                        <div class=""><small>{{ expense.getDate() }}</small></div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                {% if expense.category.id == 25 %}
                                    <span class="text-success">+{{ expense.getAmount()|number_format(2, ',', '.') }} PLN</span>
                                {% else %}
                                    <span class="text-danger">-{{ expense.getAmount()|number_format(2, ',', '.') }} PLN</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        const expenseRadio = document.querySelector("input[id=expense]");
        const incomeRadio = document.querySelector("input[id=income]");
        const categorySelectOption = document.querySelector("option[id=default]");

        expenseRadio.addEventListener('change', (event) => {
            if (document.querySelector("input[id=expense]").checked) {
                document.getElementById('expense-fields').style.display = 'block';

                const expenseDivs = document.querySelectorAll('.expense-fields');
                [].forEach.call(expenseDivs, function (div) {
                    div.style.display = 'block';
                });
                categorySelectOption.value = categorySelectOption.textContent;
            }
        });

        incomeRadio.addEventListener('change', (event) => {
            if (document.querySelector("input[id=income]").checked) {
                document.getElementById('expense-fields').style.display = 'none';

                const expenseDivs = document.querySelectorAll('.expense-fields');
                [].forEach.call(expenseDivs, function (div) {
                    div.style.display = 'none';
                });
                categorySelectOption.value = "income";
            }
        });
    </script>
{% endblock %}